src/bord/beans/Comment.java
package bord.beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    private static final long serialVersionUID = 1L;

    private int message_id;
    private int id;
    private String name;
    private String text;
    private Date createdDate;
    private String login_id;

    public int getMessageId() {
        return message_id;
    }
    public void setMessageId(int message_id) {
        this.message_id = message_id;
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public String getText() {
        return text;
    }
    public void setText(String text) {
        this.text = text;
    }

    public Date getCreatedDate() {
        return createdDate;
    }
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getLoginId() {
        return login_id;
    }
    public void setLoginId(String login_id) {
        this.login_id = login_id;
    }
}

src/bord/controller/HomeServlet.java
package bord.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import bord.beans.Comment;
import bord.beans.Message;
import bord.beans.User;
import bord.service.CommentService;
import bord.service.MessageService;

@WebServlet(urlPatterns = { "/home" })
public class HomeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        User user = (User) request.getSession().getAttribute("loginUser");

        if (user != null) {
            List<Message> messages = new MessageService().getMessage();
            request.setAttribute("messages", messages);

            List<Comment> comment = new CommentService().getComment();
            request.setAttribute("comments", comment);

            request.getRequestDispatcher("home.jsp").forward(request, response);
        }else{
            response.sendRedirect("login");
        }
    }
}

src/bord/controller/LoginServlet.java
package bord.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import bord.beans.User;
import bord.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        User user = loginService.login(loginId, password);

        HttpSession session = request.getSession();
        request.setAttribute("loginId", loginId);

        if (user != null) {

            session.setAttribute("loginUser", user);
            response.sendRedirect("home");
        } else {

            List<String> messages = new ArrayList<String>();
            messages.add("ログインに失敗しました。");
            session.setAttribute("errorMessages", messages);
            request.setAttribute("password", password);
            request.getRequestDispatcher("login.jsp").forward(request, response);
        }
    }

}

src/bord/controller/NewMessageServlet.java
package bord.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import bord.beans.Message;
import bord.beans.User;
import bord.service.MessageService;

@WebServlet(urlPatterns = { "/newMessage" })
public class NewMessageServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("newMessage.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        HttpSession session = request.getSession();

        List<String> messages = new ArrayList<String>();

        if (isValid(request, messages) == true) {

            User user = (User) session.getAttribute("loginUser");

            Message message = new Message();
            message.setText(request.getParameter("text"));
            message.setSubject(request.getParameter("subject"));
            message.setCategory(request.getParameter("category"));
            message.setName(user.getName());
            message.setLoginId(user.getLoginId());

            new MessageService().register(message);

            response.sendRedirect("home");
        } else {
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("newMessage");
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {

    	String subject = request.getParameter("subject");
    	String category = request.getParameter("category");
        String message = request.getParameter("text");

        if (StringUtils.isEmpty(subject) == true) {
            messages.add("件名を入力してください");
        } else{
        	if (30 < subject.length()) {
                messages.add("件名は30文字以下にしてください");
            }
        }
        if (StringUtils.isEmpty(category) == true) {
            messages.add("カテゴリーを入力してください");
        } else{
        	if (10 < category.length()) {
                messages.add("カテゴリーは10文字以下にしてください");
            }
        }
        if (StringUtils.isEmpty(message) == true) {
            messages.add("本文を入力してください");
        } else{
        	if (1000 < message.length()) {
                messages.add("本文は1000文字以下にしてください");
            }
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }
}

src/bord/controller/SignUpServlet.java
package bord.controller;

import static bord.utils.DBUtil.*;

import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import bord.beans.User;
import bord.dao.UserDao;
import bord.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        List<String> messages = new ArrayList<String>();

        HttpSession session = request.getSession();
        User user = new User();
        user.setLoginId(request.getParameter("loginId"));
        user.setName(request.getParameter("name"));
        user.setPassword(request.getParameter("password"));
        user.setOfficeId(Integer.parseInt(request.getParameter("officeId")));
        user.setPositionId(Integer.parseInt(request.getParameter("positionId")));
        user.setStatus(Integer.parseInt(request.getParameter("status")));


        if (isValid(request, messages) == true) {

            new UserService().register(user);

            response.sendRedirect("management");
        } else {
            session.setAttribute("errorMessages", messages);
            request.setAttribute("user", user);
            request.getRequestDispatcher("signup.jsp").forward(request, response);
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");
        String name = request.getParameter("name");
        String passwordCheck = request.getParameter("passwordCheck");
        Connection connection = null;
        connection = getConnection();
        UserDao userDao = new UserDao();

        if (StringUtils.isEmpty(loginId) == true) {
            messages.add("IDを入力してください");
        } else{
        	if (loginId.matches("^[0-9a-zA-Z]+") != true) {
                messages.add("IDは半角英数字のみで入力してください");
            }
        	if (loginId.matches(".{6,20}") != true) {
                messages.add("IDは6文字以上20文字以下にしてください");
            }
        }
        if (StringUtils.isEmpty(password) == true) {
            messages.add("パスワードを入力してください");
        } else{
//        	if (password.matches("[ -~]+") != true) {
//                messages.add("パスワードは半角英数字および記号のみで入力してください");
//        	}
        	if (password.matches("[!-~]{6,20}") != true) {
                messages.add("パスワードは6文字以上20文字以下にしてください");
            }else{
            	if (!password.equals(passwordCheck)) {
                    messages.add("パスワードが一致しません");
                }
            }
        }
        if (StringUtils.isEmpty(name) == true) {
            messages.add("名称を入力してください");
        } else{
        	if (10 < name.length()) {
                messages.add("名称は10文字以下にしてください");
            }
        }
        if(userDao.getUser(connection, loginId) != null){
        	messages.add("使用されているIDです");
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

WebContent/home.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <!-- BootstrapのCSS読み込み -->
	    <link rel="stylesheet" href="./css/bootstrap.min.css" rel="stylesheet">
	    <link href="./css/style.css" rel="stylesheet" type="text/css">
	    <!-- jQuery読み込み -->
	    <script type="text/javascript" src="./js/jquery.min.js"></script>
	    <!-- BootstrapのJS読み込み -->
	    <script src="./js/bootstrap.min.js"></script>
        <title>ホーム</title>
    </head>
    <body>
        <div class="main-contents">
                           <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
		<div class="header">
	           <ol class="breadcrumb">
			        <li class="active"><a href="home" class="btn btn-link">ホーム</a></li>
			        <li><a href="newMessage" class="btn btn-link">新規投稿</a></li>
			        <li><a href="management" class="btn btn-link">ユーザー管理</a></li>
			        <li><a href="logout" class="btn btn-link">ログアウト</a></li>
			   </ol>
			<div class="name"><h3>こんにちは、<c:out value="${loginUser.name}" />さん</h3>
        	</div><br />

	<div onclick="obj=document.getElementById('open').style; obj.display=(obj.display=='none')?'block':'none';">
	<a style="cursor:pointer;">▼投稿の絞込み クリックで展開</a>
	</div>
	<div id="open" style="display:none;clear:both;">
        <form action="findOfCategory" method="post">
	        <label class="title">カテゴリー(部分一致)</label>
	        <input name="findCategory" class="form-control" value="${findCategory}">
	        <input type="submit" class="btn btn-default" value="絞込み" >
	    </form>
	    <form action="findOfDate" method="post" class="pull-right">
	        <label class="title" for="findDate">投稿日（期間指定）</label>
	                <label class="col-md-1 col-md-offset-2">開始</label>
	                <input type="date" class="form-control" name="startDate" value="2018-09-18"/>
	                <label class="col-md-1 col-md-offset-2">終了</label>
	                <input type="date" class="form-control" name="endDate" value="2018-09-18"/>
	        <input type="submit" class="btn btn-default" value="絞込み">
		</form>
    </div>
    </div>


	 <div class="panel panel-default">
			<c:forEach items="${messages}" var="message">
			<hr size="3" color="gray">
				<form action="messageDelete" method="get">
		            	<div class="panel panel-default">
			                <div class="panel-heading">件名　　：<c:out value="${message.subject}" /></div>
			                <div class="panel-body">本文　　：<c:out value="${message.text}" /></div>
			                <div class="panel-body">投稿者　：<c:out value="${message.name}" /></div>
			                <div class="panel-footer">投稿日時：<fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			                <div class="id"><input type="hidden" name="id" value="${message.id}" /></div>
				                <c:if test="${loginUser.loginId == message.loginId}">
					                <input type="submit" class="btn btn-default btn-sm" value="削除" />
				                </c:if>
		            	</div>
		            	<hr size="3" color="gray">
		        </form>

				<c:forEach items="${comments}" var="comment">
					<c:if test="${comment.messageId == message.id}">
			            <form action="commentDelete" method="get">
				            <div class="comment">
				            	<div class="name">投稿者：<c:out value="${comment.name}" /></div>
				                <div class="text"><c:out value="${comment.text}" /></div>
				                <div class="createdDate"><fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
				                <div class="id"><input type="hidden" name="id" value="${comment.id}" /></div>
					                <c:if test="${loginUser.loginId == comment.loginId}">
					                	<input type="submit" class="btn btn-default btn-sm" value="削除" />
					                </c:if>
				            </div>
			            </form>
			            <hr>
		            </c:if>
	            </c:forEach>

	            <form action="comment" method="post">
	            <div  class="form-group">
	            	コメント<br />
            		<textarea class="form-control" name="text" cols="100" rows="5" class="commentbox"></textarea>
            		<br />
            		<div class="id"><input type="hidden" name="messageId" value="${message.id}" /></div>
            		<input type="submit" class="btn btn-default btn-sm" value="投稿">（500文字まで）
	            </div>
	            </form>
			</c:forEach>
	</div>
 		</div>
    </body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <!-- BootstrapのCSS読み込み -->
	    <link href="css/bootstrap.min.css" rel="stylesheet">
	    <link href="./css/style.css" rel="stylesheet" type="text/css">
	    <!-- jQuery読み込み -->
	    <script type="text/javascript" src="js/jquery.min.js"></script>
	    <!-- BootstrapのJS読み込み -->
	    <script src="js/bootstrap.min.js"></script>
        <title>ログイン</title>

    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <form action="login" method="post"><br />
                <label for="loginId">ログインID</label>
                <input name="loginId" value="${loginId}"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" value="${password}"/> <br />

                <input type="submit" value="ログイン" /> <br />
            </form>
        </div>
    </body>
</html>

WebContent/newMessage.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <!-- BootstrapのCSS読み込み -->
	    <link href="./css/bootstrap.min.css" rel="stylesheet">
	    <link href="./css/style.css" rel="stylesheet" type="text/css">
	    <!-- jQuery読み込み -->
	    <script type="text/javascript" src="./js/jquery.min.js"></script>
	    <!-- BootstrapのJS読み込み -->
	    <script src="./js/bootstrap.min.js"></script>
        <title>新規投稿</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">
                    <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
           <div class="header">
		        <ol class="breadcrumb">
			        <li class="active"><a href="home" class="btn btn-link">ホーム</a></li>
			        <li><a href="newMessage" class="btn btn-link">新規投稿</a></li>
			        <li><a href="management" class="btn btn-link">ユーザー管理</a></li>
			        <li><a href="logout" class="btn btn-link">ログアウト</a></li>
			   </ol>
    		</div>


<div class="form-area">
        <form action="newMessage" method="post">

         	<label for="subject">件名</label>
            <input name="subject" value="${subject}"/>（30文字まで） <br />

            <label for="category">カテゴリー</label>
            <input name="category" value="${category}"/>（10文字まで） <br />

            本文<br />
            <textarea name="text" cols="100" rows="5" class="messagebox"></textarea>
            <br />
            <input type="submit" class="btn btn-default" value="投稿">（1000文字まで）
        </form>
</div>
 		</div>
    </body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- BootstrapのCSS読み込み -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="js/bootstrap.min.js"></script>
    <title>ユーザー登録</title>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <div class="header">
		        <ol class="breadcrumb">
			        <li class="active"><a href="home" class="btn btn-link">ホーム</a></li>
			        <li><a href="newMessage" class="btn btn-link">新規投稿</a></li>
			        <li><a href="management" class="btn btn-link">ユーザー管理</a></li>
			        <li><a href="logout" class="btn btn-link">ログアウト</a></li>
			   </ol>
    		</div>
            <form action="signup" method="post">
            	<br /> <label for="loginId">ログインID</label> <input name="loginId" value="${user.loginId}" />
            	※半角英数字[azAZ0*9]で6文字以上20文字以下
            	<br /> <label for="password">パスワード</label> <input name="password" type="password" value="${user.password}" />
            	※記号を含む全ての半角文字で6文字以上20文字以下
            	<br /> <label for="passwordCheck">パスワード（確認用）</label> <input name="passwordCheck" type="password" value="${user.passwordCheck}" />
                <br /> <label for="name">名称</label> <input name="name" value="${user.name}" />
                ※10文字以下

                <br /> <label for="officeId">支店</label>
                <select name="officeId">
                <option value=1>本社</option>
                <option value=2>支店A</option>
                <option value=3>支店B</option>
                <option value=4>支店C</option>
                </select>

                <br /> <label for="positionId">部署・役職</label>
                <select name="positionId">
                <option value=1>総務人事担当者</option>
                <option value=2>情報管理担当者</option>
                <option value=3>支店長</option>
                <option value=4>社員</option>
                </select>

                <br /> <label for="status">アカウントステータス</label>
                <select name="status">
                <option value=1>有効</option>
                <option value=2>無効</option>
                </select>
                <br />
                <br /> <input type="submit" class="btn btn-default" value="登録" /> <br /> <a href="management">戻る</a>
            </form>
        </div>
    </body>
</html>